### ISSUE TITLE
NoBandwidthKick no longer working.

### ISSUE THREAD

**Issue by ChapperNi** [discord-modifications/better-discord-plugins#19]
What title says, using latest version and I'm being kicked after five minutes in a call now.

**Comment by adsdawdfawdcwacdaw** [comment]
they don't care about fixing their plugins, use this instead https://github.com/Tharki-God/BetterDiscordPlugins

**Comment by adsdawdfawdcwacdaw** [comment]
Eternal DOESN'T CARE about keeping his plugins up to date.

CommandsAPI has been broken for months, look for an alternative.

**Comment by localip** [comment]
> Eternal DOESN'T CARE about keeping his plugins up to date.
> 
> CommandsAPI has been broken for months, look for an alternative.

You make it sound like my plugins are a child meaning it's mandatory to take care of them. 
The reason I mostly stopped maintaining my plugins is because of entitled people like you. 

I am not required to update my plugins, nor do I have time for it. There is absolutely no reason for you to put words in my mouth such as "DOESN'T CARE".

**Comment by localip** [comment]
> What title says, using latest version and I'm being kicked after five minutes in a call now.

Tested on the following:

Canary 146250 (4c2ebb4)
BetterDiscord 1.6.3
Host 1.0.49 Windows 10 64-Bit (10.0.25193)

Everything seems to work, please make sure you have the latest version of ZeresPluginLibrary and of the plugin.

Perhaps you forgot to enable it?
